#ifndef SQ_STATUS_H
#define SQ_STATUS_H

typedef enum {
  SQ_OK = 0,
  SQ_ERR_ARGUMENT,
  SQ_ERR_MAGIC,
  SQ_ERR_VERSION,
  SQ_ERR_BIT_WIDTH,
  SQ_ERR_RESERVED,
  SQ_ERR_COUNT,
  SQ_ERR_PAYLOAD_LENGTH,
  SQ_ERR_SCALE,
  SQ_ERR_CODE,
  SQ_ERR_ZERO_SCALE_CODE,
  SQ_ERR_PADDING_NIBBLE,
  SQ_ERR_NONFINITE,
  SQ_ERR_SCALE_OVERFLOW,
  SQ_ERR_ID_OVERFLOW,
  SQ_ERR_MEMORY,
  SQ_ERR_IO,
  SQ_ERR_CUDA_UNAVAILABLE,
  SQ_ERR_CUDA,
  SQ_ERR_TIMINGS_BACKEND,
  SQ_ERR_CLOCK,
  SQ_ERR_AVX2_UNAVAILABLE
} sq_status;

const char *sq_status_message(sq_status status);

#endif
